# A perfect number is a positive integer that is equal to the sum of its positive divisors, excluding the number itself.
# A divisor of an integer x is an integer that can divide x evenly.
# Given an integer n, return true if n is a perfect number, otherwise return false.


def is_perfect_number(n) -> bool:
    """
    This solution generated by CodeAssistant

    """
    if n <= 1:
        return False
    divisors = [1]
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            divisors.append(i)
            if i != n // i:
                divisors.append(n // i)
    return sum(divisors) == n


if __name__ == "__main__":
    INPUT_NUMBER = 28
    print(f'{INPUT_NUMBER=} is perfect number? Answer: {
          is_perfect_number(INPUT_NUMBER)}')
